### ISSUE TITLE
.mp4 형식의 파일을 librosa가 load할 수 없는 문제

### ISSUE THREAD

**Issue by Reichidad** [ycs1m1yk/LoLHighlighter#1]

**Comment by Reichidad** [comment]
```python
directory = test.mp4
y, sr = librosa.load(directory)
```
의 코드에서 다음과 같은 warning 발생
![image](https://user-images.githubusercontent.com/47580804/78322654-52aa3d00-75aa-11ea-9709-d39dfa51059e.png)
librosa의 load 함수에서는 기본적으로 PySoundFile 라이브러리를 import해서 우리의 인풋 파일을 읽음. 이 때, soundfile failed 일 경우, audioread라는 다른 라이브러리를 통해서 인풋 파일 읽기를 재시도함. 이에 대한 안내 출력으로 확인됨. 
하지만, 이후의 실행에서 audioread 라이브러리의 함수에서도 에러가나면 피드백없이 프로세스가 종료됨. 확인해 본 결과, mp4 확장자에 대해 다룰 경우에 유사한 에러가 많이 발생하고, librosa repository의 issue 탭에서는 이와 비슷한 이슈들을 soundfile과 audioread쪽 문제라며 바로바로 이슈를 닫는 관례를 확인함.

**Comment by Reichidad** [comment]
해당 이슈에 대한 해결책으로 현재 os와 subprocess를 import하여
code로 ffmpeg의 커맨드라인을 실행하여 mp4파일을 wav파일로 변환하는 것을 시도하는 중.

**Comment by holquew** [comment]
cf16aa0089aa503781ee42ec234507879b1ab52e

임시로 파일 변환 시도

**Comment by Reichidad** [comment]
1. 위의 변환 코드가 잘 작동하는것을 확인함.
2. librosa repository의 readme 아랫부분에 해당 이슈와 관련된 내용이 언급되어있어서, 추가적인 환경을 세팅하니 mp4파일도 warning만 띄우고 잘 실행되었음.

![image](https://user-images.githubusercontent.com/47580804/78336050-b132e380-75c9-11ea-9184-5c9a3f58ef67.png)
